SELECT 
	'IF(EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = ''' + CHECKS.CONSTRAINT_NAME + ''')) ALTER TABLE ' + TABLE_NAME + ' DROP CONSTRAINT ' + CHECKS.CONSTRAINT_NAME 

FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS CHECKS INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TBL ON
(CHECKS.CONSTRAINT_NAME = TBL.CONSTRAINT_NAME)