

SET NOCOUNT ON

DECLARE @PREFIXO VARCHAR(10) = ''

DECLARE @T TABLE(LINE VARCHAR(MAX))
DECLARE @T_NAME VARCHAR(255) = '',
		@C_NAME VARCHAR(255) = '',
		@C_EXPR VARCHAR(255) = ''

DECLARE CUR_CHECK CURSOR FAST_FORWARD FOR
SELECT 
	T.TABLE_NAME, 
	C.CONSTRAINT_NAME, 
	C.CHECK_CLAUSE 
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS C INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS T ON
(C.CONSTRAINT_NAME = T.CONSTRAINT_NAME)
WHERE (ISNULL(@PREFIXO, '') = '' OR T.TABLE_NAME LIKE '%' + @PREFIXO + '%')

OPEN CUR_CHECK
FETCH NEXT FROM CUR_CHECK INTO @T_NAME, @C_NAME, @C_EXPR
WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO @T(LINE) VALUES ('IF(NOT EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(''' + @C_NAME + ''')))')
	INSERT INTO @T(LINE) VALUES ('ALTER TABLE [' + @T_NAME + '] ADD CONSTRAINT [' + @C_NAME + '] CHECK (' + @C_EXPR + ')')
	INSERT INTO @T(LINE) VALUES ('GO')

	FETCH NEXT FROM CUR_CHECK INTO @T_NAME, @C_NAME, @C_EXPR
END
CLOSE CUR_CHECK
DEALLOCATE CUR_CHECK

SELECT LINE FROM @T
SET NOCOUNT OFF

