DECLARE @PREFIXO VARCHAR(10) = ''


DECLARE @VIEW_NAME VARCHAR(500),
		@VIEW_DEF VARCHAR(MAX)

DECLARE @t TABLE(ID BIGINT IDENTITY(1,1), line VARCHAR(MAX))

DECLARE CUR_VIEWS CURSOR FAST_FORWARD FOR
SELECT DISTINCT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS
WHERE (ISNULL(@PREFIXO, '') = '' OR TABLE_NAME LIKE '%' + @PREFIXO + '%')

OPEN CUR_VIEWS
FETCH NEXT FROM CUR_VIEWS INTO @VIEW_NAME
WHILE @@FETCH_STATUS = 0
BEGIN


SET NOCOUNT ON;

    
INSERT INTO @t(line) VALUES('/*Início da view ' + @VIEW_NAME + '*/')
INSERT INTO @t(line) VALUES('IF(EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(''' + @VIEW_NAME + ''')))')
INSERT INTO @t(line) VALUES('DROP VIEW ' + @VIEW_NAME  )
INSERT INTO @t(line) VALUES('GO')    

INSERT INTO @t(line) 
EXEC SP_HELPTEXT @VIEW_NAME

INSERT INTO @t(line) VALUES('GO')
INSERT INTO @t(line) VALUES('/* Fim da view ' + @VIEW_NAME +  '*/')



FETCH NEXT FROM CUR_VIEWS INTO @VIEW_NAME

END
CLOSE CUR_VIEWS
DEALLOCATE CUR_VIEWS


SELECT line 
FROM @T
ORDER BY ID