SELECT 
	'IF(NOT EXISTS(SELECT 1 FROM CRK_RFL_TIPOCOMPONENTE WHERE ID_TIPOCOMPONENTE = ' + STR(ID_TIPOCOMPONENTE) + ')) INSERT INTO CRK_RFL_TIPOCOMPONENTE(ID_TIPOCOMPONENTE, DS_TIPOCOMPONENTE, DS_DLL, DS_CLASSE) VALUES (' + STR(ID_TIPOCOMPONENTE) + ', ''' + DS_TIPOCOMPONENTE + ''', ''' + DS_DLL + ''', ''' + DS_CLASSE + ''')'

 FROM CRK_RFL_TIPOCOMPONENTE


