SET NOCOUNT ON

DECLARE @PREFIXO VARCHAR(10) = ''

DECLARE @T TABLE(LINE VARCHAR(MAX))
DECLARE @T_NAME VARCHAR(255) = '',
		@I_NAME VARCHAR(255) = '',
		@C_NAME VARCHAR(255) = '',
		@U_INAM VARCHAR(255) = '',
		@C_1ST BIT,
		@HAS_DATA BIT = 0

DECLARE CUR_PK CURSOR FAST_FORWARD FOR
SELECT 
	T.TABLE_NAME, 
	T.CONSTRAINT_NAME,
	C.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS T INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE C ON
(T.CONSTRAINT_NAME = C.CONSTRAINT_NAME)
WHERE T.CONSTRAINT_TYPE = 'PRIMARY KEY'
AND (ISNULL(@PREFIXO, '') = '' OR T.TABLE_NAME LIKE '%' + @PREFIXO + '%')
ORDER BY T.TABLE_NAME, T.CONSTRAINT_NAME, C.ORDINAL_POSITION


OPEN CUR_PK
FETCH NEXT FROM CUR_PK INTO @T_NAME, @I_NAME, @C_NAME
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @HAS_DATA = 1
	IF(@I_NAME <> @U_INAM)
	BEGIN
		IF(@U_INAM <> '')
		BEGIN 
			INSERT INTO @T(LINE) VALUES(')')
			INSERT INTO @T(LINE) VALUES('GO')
		END
		INSERT INTO @T(LINE) VALUES('IF(NOT EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(''' + @I_NAME + ''')))')
		INSERT INTO @T(LINE) VALUES('ALTER TABLE DBO.' + @T_NAME + ' ADD CONSTRAINT ' + @I_NAME + ' PRIMARY KEY(')
		SET @C_1ST = 1
	END
	
	INSERT INTO @T(LINE) VALUES(CASE WHEN @C_1ST = 0 THEN ',' ELSE '' END + @C_NAME)
	SET @C_1ST = 0
	SET @U_INAM = @I_NAME
	
	FETCH NEXT FROM CUR_PK INTO @T_NAME, @I_NAME, @C_NAME
END
CLOSE CUR_PK
DEALLOCATE CUR_PK

IF(@HAS_DATA = 1)
	INSERT INTO @T(LINE) VALUES(')')
	
INSERT INTO @T(LINE) VALUES('GO')	


SELECT LINE FROM @T

SET NOCOUNT OFF