SET NOCOUNT ON

DECLARE @PREFIXO VARCHAR(10) = ''
DECLARE @T TABLE(LINE VARCHAR(MAX))
DECLARE @T_NAME VARCHAR(255),
		@TR_NAME VARCHAR(255)


DECLARE CUR_TRG CURSOR FAST_FORWARD FOR
SELECT
    [so].[name] AS [trigger_name],
    OBJECT_NAME([so].[parent_obj]) AS [table_name]
FROM sysobjects AS [so]
INNER JOIN sysobjects AS so2 ON so.parent_obj = so2.Id
WHERE [so].[type] = 'TR'
AND (ISNULL(@PREFIXO, '') = '' OR SO.PARENT_OBJ LIKE '%' + @PREFIXO + '%')

OPEN CUR_TRG
FETCH NEXT FROM CUR_TRG INTO @TR_NAME, @T_NAME
WHILE @@FETCH_STATUS = 0
BEGIN
	
	INSERT INTO @T(LINE) VALUES('IF(EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID(''' + @TR_NAME + ''')))')
	INSERT INTO @T(LINE) VALUES('DROP TRIGGER DBO.' + @TR_NAME)
	INSERT INTO @T(LINE) VALUES('GO')
	
	INSERT INTO @T
	EXEC SP_HELPTEXT @TR_NAME

	INSERT INTO @T(LINE) VALUES ('GO')

	FETCH NEXT FROM CUR_TRG INTO @TR_NAME, @T_NAME
END
CLOSE CUR_TRG
DEALLOCATE CUR_TRG

INSERT INTO @T(LINE) VALUES ('GO')

SELECT LINE FROM @T

SET NOCOUNT OFF